// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaQK3u_e-R12zgvHVJ9GB4jwltFzQ_B4c',
    appId: '1:126991382142:web:d55368c5f49548216cca2f',
    messagingSenderId: '126991382142',
    projectId: 'whatup-clone-app',
    authDomain: 'whatup-clone-app.firebaseapp.com',
    storageBucket: 'whatup-clone-app.appspot.com',
    measurementId: 'G-FW6J7YLH1S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoy9DOuMToL7I4ToC__n5VRem6Wh1JZoM',
    appId: '1:126991382142:android:557bf36f0541ac5e6cca2f',
    messagingSenderId: '126991382142',
    projectId: 'whatup-clone-app',
    storageBucket: 'whatup-clone-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEI3lN13ZAJiqABI_49Sed888OaJKhsLE',
    appId: '1:126991382142:ios:d7a146102620f78f6cca2f',
    messagingSenderId: '126991382142',
    projectId: 'whatup-clone-app',
    storageBucket: 'whatup-clone-app.appspot.com',
    iosClientId:
        '126991382142-estv2p4m4nlq0ii575q3rsfhqomr7b2o.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappUi',
  );
}
